### ISSUE TITLE
Template directories not working in master branch

### ISSUE THREAD

**Issue by areyoufeelingitnowmrkrebs** [eylles/pywal16#110]
They were working before but now they're not. Unsure what could have caused it but here is the error output, which mentions some stuff about errors in the actual script as well.

```
Traceback (most recent call last):
  File "/home/ego/.local/bin/wal", line 8, in <module>
    sys.exit(main())
             ~~~~^^
  File "/home/ego/.local/lib/python3.13/site-packages/pywal/__main__.py", line 340, in main
    parse_args(parser)
    ~~~~~~~~~~^^^^^^^^
  File "/home/ego/.local/lib/python3.13/site-packages/pywal/__main__.py", line 317, in parse_args
    export.every(colors_plain)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/ego/.local/lib/python3.13/site-packages/pywal/export.py", line 132, in every
    template(colors, file.path, join(output_dir, file.name))
    ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ego/.local/lib/python3.13/site-packages/pywal/export.py", line 17, in template
    template_data = util.read_file_raw(input_file)
  File "/home/ego/.local/lib/python3.13/site-packages/pywal/util.py", line 211, in read_file_raw
    with open(input_file, "r") as file:
         ~~~~^^^^^^^^^^^^^^^^^
IsADirectoryError: [Errno 21] Is a directory: '/home/ego/.config/wal/templates/Kvantum'
```

Just wanted to point this out in case it's going to be a problem for the next release.

**Comment by eylles** [comment]
hmmmm weird how it is error-ing out, will have to check that thoroughly before cutting a release.

**Comment by areyoufeelingitnowmrkrebs** [comment]
I have no idea what was wrong but I just reinstalled and it's working again.

**Comment by jude7733** [comment]
for me the .cache directory is not updated. reinstalled and nothing changed...

**Comment by eylles** [comment]
> **error**
> 
> FileNotFoundError: [Errno 2] No such file or directory: 'hyprpaper'
> 
> but i'm using swww so y should i need a hyprpaper config/command

full error?

**Comment by jude7733** [comment]
> full error?

Traceback (most recent call last):
  File "/usr/bin/wal", line 33, in <module>
    sys.exit(load_entry_point('pywal16==3.8.0', 'console_scripts', 'wal')())
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/pywal/__main__.py", line 336, in main
    parse_args(parser)
    ~~~~~~~~~~^^^^^^^^
  File "/usr/lib/python3.13/site-packages/pywal/__main__.py", line 306, in parse_args
    wallpaper.change(colors_plain["wallpaper"])
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/pywal/wallpaper.py", line 356, in change
    set_desktop_wallpaper(desktop, img)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/pywal/wallpaper.py", line 182, in set_desktop_wallpaper
    util.disown(["hyprpaper"])
    ~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/pywal/util.py", line 340, in disown
    subprocess.Popen(cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/subprocess.py", line 1038, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                        pass_fds, cwd, env,
                        ^^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
                        gid, gids, uid, umask,
                        ^^^^^^^^^^^^^^^^^^^^^^
                        start_new_session, process_group)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/subprocess.py", line 1974, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'hyprpaper'

**Comment by eylles** [comment]
@jude7733 pywal 3.8.0 or from master?

**Comment by jude7733** [comment]
Release 3.8 - arch Linux

**Comment by eylles** [comment]
yeh, commit: ac425c0e5ed400c4284e78652f03bd2176dd0a4f fixed the support for hyprland and hyprpaper but is not until commit: 12ea5af3c6796c5f516c33251032cd96d3a4f747 from 2 days ago that hyprland and hyprpaper is "properly" working, mind you i say "properly" since i do not use hyprland or wayland for that matter but just going from the documentation it should actually work as intended this time.

give me a moment to update the changelog, bump the version and i'll have a new release on pypi ready to install, no idea how long until it'll hit the AUR tho as i got no control over that.

**Comment by eylles** [comment]
@jude7733 well i'm glad to say that pywal16 3.8.1 is already available at [pypi](https://pypi.org/project/pywal16/)

you can uninstall the AUR package and install with pip like indicated on the wiki [Installation](https://github.com/eylles/pywal16/wiki/Installation)

if you do want the AUR package consider giving a shoutout to the maintainer https://aur.archlinux.org/packages/python-pywal16

**Comment by jude7733** [comment]
> @jude7733 well i'm glad to say that pywal16 3.8.1 is already available at [pypi](https://pypi.org/project/pywal16/)
> 
> you can uninstall the AUR package and install with pip like indicated on the wiki [Installation](https://github.com/eylles/pywal16/wiki/Installation)
> 
> if you do want the AUR package consider giving a shoutout to the maintainer https://aur.archlinux.org/packages/python-pywal16

Thanks a lot ! @eylles

**Comment by jude7733** [comment]
aur got updated too wew, everything is working
