### ISSUE TITLE
Wal command doesn't work

### ISSUE THREAD

**Issue by TheRealA77** [eylles/pywal16#111]
I started getting this error after updating my system (Arch Linux) and all packages to the latest version

```
[thereala77@PC-Arch ~]$ wal -I $BG
Traceback (most recent call last):
  File "/usr/lib/python3.13/importlib/metadata/__init__.py", line 407, in from_name
    return next(iter(cls.discover(name=name)))
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/wal", line 33, in <module>
    sys.exit(load_entry_point('pywal16==3.7.2', 'console_scripts', 'wal')())
             ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/wal", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
                       ~~~~~~~~~~~~^^^^^^^^^^^
  File "/usr/lib/python3.13/importlib/metadata/__init__.py", line 960, in distribution
    return Distribution.from_name(distribution_name)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/importlib/metadata/__init__.py", line 409, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for pywal16
```

**Comment by Ly-sec** [comment]
It has to be rebuilt, just like most things that are using python (most stuff updated to a newer version).

**Comment by eylles** [comment]
when in doubt blame the AUR

**Comment by TheRealA77** [comment]
I reinstalled it from the AUR and it works now, it just needed to be rebuilt. Thank you for the suggestions
