### ISSUE TITLE
KeyError: 'DESKTOP_SESSION'

### ISSUE THREAD

**Issue by asimovc** [eylles/pywal16#52]
I get this error when i test a wallpaper and wal cant generate the files with colors

```
(pywal16) [user@tux ~/pywal16]$ wal -n -i ~/Wallpapers/wallhaven-5gp7j8_1920x1080.png 
[I] image: Using image wallhaven-5gp7j8_1920x1080.png.
[I] theme: Set theme to _home_hellboy_Wallpapers_wallhaven-5gp7j8_1920x1080_png_9_dark_None_None_2774760_1.1.0.json.
[I] colors: Found cached colorscheme.
Traceback (most recent call last):
  File "/home/user/pywal16/bin/wal", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/user/pywal16/lib/python3.12/site-packages/pywal/__main__.py", line 244, in main
    parse_args(parser)
  File "/home/user/pywal16/lib/python3.12/site-packages/pywal/__main__.py", line 216, in parse_args
    sequences.send(colors_plain, to_send=not args.s, vte_fix=args.vte)
  File "/home/user/pywal16/lib/python3.12/site-packages/pywal/sequences.py", line 93, in send
    if os.environ["DESKTOP_SESSION"] == "plasma":
       ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "<frozen os>", line 685, in __getitem__
KeyError: 'DESKTOP_SESSION'
```

**Comment by eylles** [comment]
huh so that is a direct consequence of https://github.com/eylles/pywal16/pull/51

what distro and desktop environment are you on?

cc @Acetylsalicylsaeure

**Comment by asimovc** [comment]
My distro is Gentoo and i'm not using any desktop environment, i just use a compositor window manager called dwl.

**Comment by eylles** [comment]
the `os.environ`  expects the variable `DESKTOP_SESSION` to exist and have some value even if empty, should have catched that back before merging the pr, i guess you really cannot assume any env var to be set by the user session.

**Comment by eylles** [comment]
fixed in https://github.com/eylles/pywal16/commit/8aad28a33ec30cd03836296813355f43b5546724
